(function(){const e=document.getElementById('dots');if(e){for(let i=0;i<42;i++){const d=document.createElement('div');d.className='dot';d.style.cssText=`position:absolute;left:${Math.random()*100}%;top:${Math.random()*100}%;width:${1+Math.random()*1.5}px;height:${1+Math.random()*1.5}px;--d:${3+Math.random()*4}s;--o:${.2+Math.random()*.4};animation-delay:${Math.random()*5}s;border-radius:50%`;e.appendChild(d)}}})();
addEventListener('mousemove',e=>{const g=document.getElementById('glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
function toggleTheme(){const h=document.documentElement,n=h.getAttribute('data-theme')==='dark'?'light':'dark';h.setAttribute('data-theme',n);localStorage.setItem('theme',n);document.getElementById('themeBtn').textContent=n==='dark'?'🌙':'☀️'}
(function(){const s=localStorage.getItem('theme');if(s){document.documentElement.setAttribute('data-theme',s);const b=document.getElementById('themeBtn');if(b)b.textContent=s==='dark'?'🌙':'☀️'}})();
async function copyPromo(code,el){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(code)}else{const t=document.createElement('textarea');t.value=code;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.focus();t.select();document.execCommand('copy');t.remove()}const label=el.querySelector('.promo-l'),old=label.textContent;label.textContent='✅ Промокод скопирован';setTimeout(()=>label.textContent=old,1700)}catch(e){alert('Не удалось скопировать промокод')}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderReview(){
  const data=window.PAYTAOFF_REVIEWS[window.CURRENT_REVIEW]; if(!data)return;
  document.title=`${data.n} обзор 2026 — бонусы, игры и вывод | Paytaoff`;
  document.querySelector('meta[name="description"]').setAttribute('content',`Обзор ${data.n}: бонусы, игры, плюсы и минусы, кому подойдёт казино, промокод, вывод денег и честная оценка Paytaoff. 18+`);
  document.querySelector('link[rel="canonical"]').setAttribute('href',`https://www.paytaoff.ru/reviews/${window.CURRENT_REVIEW}/`);
  const promo=data.p?`<div class="promo" onclick="copyPromo('${esc(data.p)}', this)"><div class="promo-l">📋 Промокод — нажми, чтобы скопировать</div><div class="promo-c">${esc(data.p)}</div><div class="promo-d">${esc(data.pd)}</div></div>`:'';
  const tags=data.tags.map(x=>`<span class="tag">✓ ${esc(x)}</span>`).join('');
  const pros=data.pros.map(x=>`<li>${esc(x)}</li>`).join('');
  const cons=data.cons.map(x=>`<li>${esc(x)}</li>`).join('');
  const others=Object.entries(window.PAYTAOFF_REVIEWS).filter(([k])=>k!==window.CURRENT_REVIEW).slice(0,5).map(([k,c])=>`<a class="other" href="/reviews/${k}/"><img src="${esc(c.i)}" alt="${esc(c.n)}"><div class="other-n">${esc(c.e)} ${esc(c.n)}</div><div class="other-b">${esc(c.b)}</div></a>`).join('');
  document.getElementById('app').innerHTML=`
  <section class="glass hero"><div><div class="badge">${esc(data.e)} Обзор казино 2026</div><h1>${esc(data.n)}: <span class="gt">обзор, бонусы и вывод</span></h1><p class="lead"><strong>${esc(data.n)}</strong> — ${esc(data.l)}</p><div class="rate-row"><div class="chip">⭐ ${esc(data.r)} / 10</div><div class="chip">🎁 ${esc(data.b)}</div><div class="chip">🔞 18+</div></div><div class="bonus-box"><div class="bonus-l">Стартовый бонус</div><div class="bonus-v">${esc(data.b)}</div></div>${promo}<div class="hero-actions"><a href="${esc(data.u)}" target="_blank" rel="nofollow sponsored noopener" class="cta">Перейти в ${esc(data.n)} →</a><a href="/quiz/" class="cta cta-ghost">🎯 Пройти тест</a></div></div><div class="hero-img"><img src="${esc(data.i)}" alt="${esc(data.n)} обзор" loading="eager"></div></section>
  <section class="grid"><div class="card glass"><h3>Кому подойдёт</h3><p>${esc(data.tags.join(', '))}</p></div><div class="card glass"><h3>Игры</h3><p>Слоты, live-раздел, бонусные игры и популярные форматы. Перед игрой проверь актуальный список игр на сайте казино.</p></div><div class="card glass"><h3>Платежи</h3><p>Перед депозитом проверь методы оплаты, лимиты, сроки вывода и требования к верификации.</p></div></section>
  <section class="glass section"><h2>Краткий вывод</h2><p>${esc(data.v)}</p><div class="tags">${tags}</div></section>
  <section class="glass section"><h2>Плюсы и минусы ${esc(data.n)}</h2><div class="two"><div><h3>Плюсы</h3><ul class="clean good">${pros}</ul></div><div><h3>Что учесть</h3><ul class="clean bad">${cons}</ul></div></div></section>
  <section class="glass section"><h2>Бонус и промо</h2><p>Главное предложение ${esc(data.n)}: <strong>${esc(data.b)}</strong>. Перед активацией бонуса обязательно проверь правила, минимальный депозит, вейджер, сроки действия и ограничения по играм.</p><div class="risk"><strong>Важно:</strong> бонусы могут меняться. Информация носит обзорный характер. Играй только 18+ и не воспринимай азартные игры как способ заработка.</div></section>
  <section class="glass section"><h2>FAQ по ${esc(data.n)}</h2><div class="faq"><div class="faq-item"><button class="faq-q" type="button"><span>${esc(data.n)} подойдёт новичку?</span><span class="faq-plus">+</span></button><div class="faq-a">Да, если тебе подходит бонусный формат и ты заранее читаешь правила. Новичкам особенно важно начинать с небольших сумм.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>Как получить бонус?</span><span class="faq-plus">+</span></button><div class="faq-a">Обычно бонус активируется при регистрации или первом депозите. Если есть промокод, его нужно ввести в специальное поле.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>Можно ли играть с телефона?</span><span class="faq-plus">+</span></button><div class="faq-a">Большинство современных казино адаптированы под мобильный экран. Проверь удобство кабинета, депозита и вывода.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>На что смотреть перед депозитом?</span><span class="faq-plus">+</span></button><div class="faq-a">Смотри правила бонуса, вейджер, лимиты на вывод, методы оплаты, сроки обработки заявок и требования к верификации.</div></div></div></section>
  <section class="glass section"><h2>Другие обзоры казино</h2><p>Если хочешь сравнить варианты, посмотри соседние обзоры Paytaoff.</p><div class="other-grid">${others}</div></section>`;
  document.querySelectorAll('.faq-q').forEach(btn=>{btn.addEventListener('click',()=>{const item=btn.closest('.faq-item'),answer=item.querySelector('.faq-a'),active=item.classList.contains('on');document.querySelectorAll('.faq-item').forEach(el=>{el.classList.remove('on');const a=el.querySelector('.faq-a');if(a)a.style.maxHeight=null});if(!active){item.classList.add('on');answer.style.maxHeight=answer.scrollHeight+'px'}})});
}
document.addEventListener('DOMContentLoaded',renderReview);
