(function(){const e=document.getElementById('dots');if(e){for(let i=0;i<42;i++){const d=document.createElement('div');d.className='dot';d.style.cssText=`position:absolute;left:${Math.random()*100}%;top:${Math.random()*100}%;width:${1+Math.random()*1.5}px;height:${1+Math.random()*1.5}px;--d:${3+Math.random()*4}s;--o:${.2+Math.random()*.4};animation-delay:${Math.random()*5}s;border-radius:50%`;e.appendChild(d)}}})();
addEventListener('mousemove',e=>{const g=document.getElementById('glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
function toggleTheme(){const h=document.documentElement,n=h.getAttribute('data-theme')==='dark'?'light':'dark';h.setAttribute('data-theme',n);localStorage.setItem('theme',n);document.getElementById('themeBtn').textContent=n==='dark'?'🌙':'☀️'}
(function(){const s=localStorage.getItem('theme');if(s){document.documentElement.setAttribute('data-theme',s);const b=document.getElementById('themeBtn');if(b)b.textContent=s==='dark'?'🌙':'☀️'}})();
async function copyPromo(code,el){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(code)}else{const t=document.createElement('textarea');t.value=code;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.focus();t.select();document.execCommand('copy');t.remove()}const label=el.querySelector('.promo-l'),old=label.textContent;label.textContent='✅ Promokod nusxalandi';setTimeout(()=>label.textContent=old,1700)}catch(e){alert('Promokodni nusxalab bo‘lmadi')}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderReview(){
  const data=window.PAYTAOFF_UZ_REVIEWS[window.CURRENT_REVIEW]; if(!data)return;
  document.title=`${data.n} sharhi 2026 — bonuslar, o‘yinlar va pul yechish | Paytaoff`;
  document.querySelector('meta[name="description"]').setAttribute('content',`${data.n} sharhi: bonuslar, o‘yinlar, plus va minuslar, kimga mosligi, promokod, pul yechish va Paytaoff bahosi. 18+`);
  document.querySelector('link[rel="canonical"]').setAttribute('href',`https://www.paytaoff.ru/uz/reviews/${window.CURRENT_REVIEW}/`);
  const promo=data.p?`<div class="promo" onclick="copyPromo('${esc(data.p)}', this)"><div class="promo-l">📋 Promokod — nusxalash uchun bosing</div><div class="promo-c">${esc(data.p)}</div><div class="promo-d">${esc(data.pd)}</div></div>`:'';
  const tags=data.tags.map(x=>`<span class="tag">✓ ${esc(x)}</span>`).join('');
  const pros=data.pros.map(x=>`<li>${esc(x)}</li>`).join('');
  const cons=data.cons.map(x=>`<li>${esc(x)}</li>`).join('');
  const others=Object.entries(window.PAYTAOFF_UZ_REVIEWS).filter(([k])=>k!==window.CURRENT_REVIEW).slice(0,5).map(([k,c])=>`<a class="other" href="/uz/reviews/${k}/"><img src="${esc(c.i)}" alt="${esc(c.n)}"><div class="other-n">${esc(c.e)} ${esc(c.n)}</div><div class="other-b">${esc(c.b)}</div></a>`).join('');
  document.getElementById('app').innerHTML=`
  <section class="glass hero"><div><div class="badge">${esc(data.e)} Kazino sharhi 2026</div><h1>${esc(data.n)}: <span class="gt">sharh, bonuslar va pul yechish</span></h1><p class="lead"><strong>${esc(data.n)}</strong> — ${esc(data.l)}</p><div class="rate-row"><div class="chip">⭐ ${esc(data.r)} / 10</div><div class="chip">🎁 ${esc(data.b)}</div><div class="chip">🔞 18+</div></div><div class="bonus-box"><div class="bonus-l">Start bonusi</div><div class="bonus-v">${esc(data.b)}</div></div>${promo}<div class="hero-actions"><a href="${esc(data.u)}" target="_blank" rel="nofollow sponsored noopener" class="cta">${esc(data.n)} saytiga o‘tish →</a><a href="/uz/quiz/" class="cta cta-ghost">🎯 Testdan o‘tish</a></div></div><div class="hero-img"><img src="${esc(data.i)}" alt="${esc(data.n)} sharhi" loading="eager"></div></section>
  <section class="grid"><div class="card glass"><h3>Kimga mos?</h3><p>${esc(data.tags.join(', '))}</p></div><div class="card glass"><h3>O‘yinlar</h3><p>Slotlar, live bo‘lim, bonus o‘yinlar va ommabop formatlar. O‘ynashdan oldin kazino saytida aktual o‘yinlar ro‘yxatini tekshiring.</p></div><div class="card glass"><h3>To‘lovlar</h3><p>Depozitdan oldin to‘lov usullari, limitlar, pul yechish muddati va verifikatsiya talablarini tekshirish kerak.</p></div></section>
  <section class="glass section"><h2>Qisqa xulosa</h2><p>${esc(data.v)}</p><div class="tags">${tags}</div></section>
  <section class="glass section"><h2>${esc(data.n)} plus va minuslari</h2><div class="two"><div><h3>Pluslar</h3><ul class="clean good">${pros}</ul></div><div><h3>Nimani hisobga olish kerak?</h3><ul class="clean bad">${cons}</ul></div></div></section>
  <section class="glass section"><h2>Bonus va promo</h2><p>${esc(data.n)} asosiy taklifi: <strong>${esc(data.b)}</strong>. Bonusni faollashtirishdan oldin qoidalar, minimal depozit, veyjer, amal qilish muddati va o‘yin cheklovlarini tekshiring.</p><div class="risk"><strong>Muhim:</strong> bonuslar o‘zgarishi mumkin. Ma’lumot sharh xarakterida. Faqat 18+ va mas’uliyatli o‘yin tamoyiliga amal qiling. Qimor o‘yinlarini daromad usuli deb qabul qilmang.</div></section>
  <section class="glass section"><h2>${esc(data.n)} bo‘yicha FAQ</h2><div class="faq"><div class="faq-item"><button class="faq-q" type="button"><span>${esc(data.n)} yangi boshlovchiga mosmi?</span><span class="faq-plus">+</span></button><div class="faq-a">Ha, agar bonus formati sizga mos bo‘lsa va qoidalarni oldindan o‘qisangiz. Yangi foydalanuvchilar kichik summadan boshlagani ma’qul.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>Bonusni qanday olish mumkin?</span><span class="faq-plus">+</span></button><div class="faq-a">Odatda bonus ro‘yxatdan o‘tish yoki birinchi depozit vaqtida faollashadi. Agar promokod bo‘lsa, uni maxsus maydonga kiritish kerak.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>Telefondan o‘ynash mumkinmi?</span><span class="faq-plus">+</span></button><div class="faq-a">Ko‘p zamonaviy kazinolar mobil ekran uchun moslashtirilgan. Shaxsiy kabinet, depozit va pul yechish qulayligini tekshiring.</div></div><div class="faq-item"><button class="faq-q" type="button"><span>Depozitdan oldin nimaga qarash kerak?</span><span class="faq-plus">+</span></button><div class="faq-a">Bonus qoidalari, veyjer, pul yechish limitlari, to‘lov usullari, arizalarni ko‘rib chiqish muddati va verifikatsiya talablariga qarang.</div></div></div></section>
  <section class="glass section"><h2>Boshqa kazino sharhlari</h2><p>Variantlarni taqqoslamoqchi bo‘lsangiz, Paytaoff’dagi boshqa sharhlarni ham ko‘ring.</p><div class="other-grid">${others}</div></section>`;
  document.querySelectorAll('.faq-q').forEach(btn=>{btn.addEventListener('click',()=>{const item=btn.closest('.faq-item'),answer=item.querySelector('.faq-a'),active=item.classList.contains('on');document.querySelectorAll('.faq-item').forEach(el=>{el.classList.remove('on');const a=el.querySelector('.faq-a');if(a)a.style.maxHeight=null});if(!active){item.classList.add('on');answer.style.maxHeight=answer.scrollHeight+'px'}})});
}
document.addEventListener('DOMContentLoaded',renderReview);
